#ifndef ARCH_X86_SEGMENTS_H
#define ARCH_X86_SEGMENTS_H

#define GDT_SELECTOR_KERNEL_CODE 0x18
#define GDT_SELECTOR_KERNEL_DATA 0x20
#define GDT_SELECTOR_USER_CODE   0x28
#define GDT_SELECTOR_USER_DATA   0x30

#endif
